service: deploy-example
frameworkVersion: '3'

plugins:
 - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: 'us-east-2'
  versionFunctions: false

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  hello2:
    handler: handler.hello
    events:
      - http:
          path: /batatas
          method: get
